### PR TITLE
Update JS docs to new `languages` key in settings

### PR DESCRIPTION
**Pull request by calebmeyer**
This confused me for a minute, trying to turn off JS format on save

### CODE REVIEW

**Comment by JosephTLyons** [comment]
Hey @calebmeyer, did using `language_overrides` not work for you when trying to turn off JS format on save?  If so, that might be a bug, as I *believe* `langauge_overrides` is the correct thing.  I'll have to double check with someone else on the team.

**Comment by JosephTLyons** [comment]
Just to double check, this doesn't work for you?

```json
"language_overrides": {
    "JavaScript": {
        "format_on_save": "off"
    },
}
```

Flipping this setting worked on my end

**Comment by calebmeyer** [comment]
Apparently it's working for me now. Must have had a typo previously. Thanks for following up!

**Comment by calebmeyer** [comment]
And it's back? I took today's update, and none of my settings get applied with that in my settings.json:
image
image

**Comment by calebmeyer** [comment]
Here's my settings if it matters: https://gist.github.com/calebmeyer/7fb66dc1486f4b0dfc9fa897ae2c5d6d

**Pull request closed without merging**
